### PR TITLE
Admin privileges are needed to run the pre-flight-check test

### PR DESCRIPTION
**Pull request by brenton**
Not all our AMIs have docker configured to allow Docker actions to happen as
non-root.  Until we can get that sorted out we need to use sudo.

### CODE REVIEW

**Comment by brenton** [comment]
[test]

**Comment by brenton** [comment]
[merge]

**Comment by rhcarvalho** [comment]
[food-for-thought]

@brenton @stevekuznetsov, thinking about the "API" of the new CI tooling, maybe this is one example where what I would like `make test-integration` to do on my machine differs from what I need it to do in CI.

If our only interface is the Makefile, and we cannot change the `make` invocation (to make it e.g. `sudo make ...`), then if we also want to be able to run without sudo locally, I suspect we need to Make Targets.

If CI was configured like Travis, we could remove sudo from the Makefile, and change the `make` invocation.

[/food-for-thought]

**Comment by stevekuznetsov** [comment]
Hmm... not sure how this case generalizes, since the "correct" fix for this (i.e. talking with the Docker daemon) is to do it as a user in the `docker` group -- this should be the case locally, on CI, wherever. Is there a case where you can see _always_ wanting to run differently on your local dev environment versus a remote one, all other things being equal, the remote AMI being set up correctly, etc?

**Comment by brenton** [comment]
I suspect we have a few base AMI fixes that are needed.  I know we need to preinstall a few deps to speed up the test run.  As a hack I'm installing the deps in the test job.  If we need to add the user to the docker group we can do it and then remove this hack.

**Comment by stevekuznetsov** [comment]
The `ec2-user` should be in the `docker` group, Origin tests like `test/end-to-end/core.sh` execute commands with the Docker daemon client tools and don't use `sudo` AFAIK.

**Comment by stevekuznetsov** [comment]
This is for the `base_ami` and `devenv_ami` that get created on the external Jenkins, that is.

**Comment by brenton** [comment]
@stevekuznetsov, what I noticed is that it worked for the RHEL ami but not for the centos AMI.

**Comment by stevekuznetsov** [comment]
The `openvswitch` RPM was missing from CentOS sources for a couple months now, I don't think we've published a CentOS AMI in quite a long time -- when was the one you were using created? Sorry that this is the answer, but historically I don't think anyone used that AMI, so it failing went un-noticed. I've been focusing on getting `origin-ci-tool` ready instead of patching up un-used holes in `vagrant-openshit`.

**Comment by rhcarvalho** [comment]
> Is there a case where you can see always wanting to run differently on your local dev environment versus a remote one

I can't think of one at the moment. I agree with you, ideally it should be the same command, if there are differences it should just be to prepare the CI env in some special way if needed (but since we control the CI env, these shouldn't be needed).

**Comment by stevekuznetsov** [comment]
@brenton In the near future CentOS AMI will be blocked on having Docker 1.12, until CentOS 7.3 is out.

**Comment by rhcarvalho** [comment]
>> Is there a case where you can see always wanting to run differently on your local dev environment versus a remote one
> 
> I can't think of one at the moment.

@stevekuznetsov I might have one use case for Go: I'd let CI always run tests with the race detector enabled, but for efficiency and quick feedback cycles when developing (TDD), it's normally a better idea to run tests without `-race` most of the time, and enable it when we're happy with what we have so far.

Thoughts?

(that's more for other projects e.g. origin and source-to-image; here, though we're writing tests in Go, the race detector is probably of no much value, since we only use the test framework to call out ansible-playbook)

**Comment by stevekuznetsov** [comment]
Good thought. In Origin we have chosen to expose these types of things as environment variables and then run:

```sh
$ make test-unit DETECT_RACES=true
```

The rationale being that it's not unreasonable for someone to run with the detector on, locally. All of our tests in Origin that are currently calling `make` targets or scripts run with some set of environment variables set to tune in the behavior we want.

**Pull request merged**
